site_name: Calculus
repo_url: https://github.com/dmccreary/calculus
site_url: https://dmccreary.github.io/calculus/
site_description: An interactive intelligent textbook for AP calculus designed for college credit.
site_author: Dan McCreary

nav:
  - Home: index.md
  - About the Course: about.md
  - Course Description: course-description.md
  
  - Chapters:
    - Overview: chapters/index.md
    - 1. Introduction to Calculus:
      - Content: chapters/01-intro/index.md
      - Quiz: chapters/01-intro/quiz.md
      - References: chapters/01-intro/references.md
    
  - MicroSims:
    - List of MicroSims: sims/index.md
    - Graph Viewer: sims/graph-viewer/index.md
    
  - Learning Graph:
    - Introduction: learning-graph/index.md
    - Course Description Assessment: learning-graph/course-description-assessment.md
    - Concept List: learning-graph/concept-list.md
    - Quality Metrics: learning-graph/quality-metrics.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Taxonomy Distribution: learning-graph/taxonomy-distribution.md
    - Glossary Quality Report: learning-graph/glossary-quality-report.md
    - FAQ Quality Report: learning-graph/faq-quality-report.md
    - Quiz Generation Report: learning-graph/quiz-generation-report.md
  
  - Sample Prompts:
    - List of Prompts: prompts/index.md

  - Glossary: glossary.md
  - FAQ: faq.md
  - License: license.md
  - Contact: contact.md

theme:
  name: material
  # logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'purple'
    accent: 'white'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.action.edit

plugins:
  - search
  #- social
  #- social_override

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - docs
  - mkdocs.yml

extra:
  schema: https://dmccreary.github.io/intelligent-textbooks/ns/textbook/v1
  textbook_name: Calculus
  textbook_version: "1.0"
  #analytics:
  #  provider: google
  #  property: G-####
